version: 0.2

phases:
  install:
    commands:
      - echo Build started on `date`
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - IMAGE_TAG=latest-$IMAGE_ARCH
      - echo ECR_URI=$ECR_URI
      - echo IMAGE_NAME=$IMAGE_NAME
      - echo IMAGE_TAG=$IMAGE_TAG
      - echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - echo Build image ...
      - docker build -t $ECR_URI/$IMAGE_NAME:$IMAGE_TAG .
      - docker images
  post_build:
    commands:
      - docker push $ECR_URI/$IMAGE_NAME:$IMAGE_TAG
      - echo Build completed on `date`
