name: Continuous integration

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  cfn-nag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  build-unicorn-store:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: mvn db-setup
        run: ./mvnw package -f infrastructure/db-setup/pom.xml
        working-directory: ./labs/unicorn-store
      - name: mvn cdk
        run: ./mvnw package -f infrastructure/cdk/pom.xml
        working-directory: ./labs/unicorn-store
      - name: mvn unicorn-store-spring
        run: ./mvnw package -f software/unicorn-store-spring/pom.xml
        working-directory: ./labs/unicorn-store
      - name: install cdk
        run: npm install -g aws-cdk
      - name: synth
        run: cdk synth
        working-directory: ./labs/unicorn-store/infrastructure/cdk
